config/routes.rb
Rails.application.routes.draw do
  constraints Clearance::Constraints::SignedIn.new do
    root to: "dashboards#show", as: :signed_in_root
  end

  constraints Clearance::Constraints::SignedOut.new do
    root to: "homes#show"
  end
  
  resources :questions, except: [:index] do
    resources :answers, except: [:index]
  end

  resources :answers do
    member do
      post "upvote" => "upvotes#create", as: :upvote
      delete "unvote" => "upvotes#destroy", as: :unvote
    end
  end

  resources :passwords, controller: "clearance/passwords", only: [:create, :new]
  resource :session, only: [:create]

  resources :users, only: [:create, :show, :edit, :update] do
    resource :password,
      controller: "clearance/passwords",
      only: [:create, :edit, :update]
  end

  get "/sign_in" => "sessions#new", as: "sign_in"
  delete "/sign_out" => "sessions#destroy", as: "sign_out"
  get "/sign_up" => "users#new", as: "sign_up"
  get "/auth/:provider/callback" => "sessions#create_from_omniauth"
  get "/unanswered" => "dashboards#unanswered", as: "unanswered"
end

app/models/question.rb
class Question < ApplicationRecord
  has_many :answers, dependent: :destroy

  belongs_to :user
  has_many :respondents, through: :answers, source: :users

  has_one_attached :image, dependent: :destroy

  validates :title, presence: true, length: { in: 1... 100 }
  validates :body, presence: true, length: { in: 1... 1000 }

  default_scope { order(created_at: :desc) }
  scope :unanswered, -> { unscoped.includes(:answers).where(answers: { id: nil }) }

  delegate :username, to: :user # blocks law of demeter violation in _question
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :set_question, only: [:show, :edit, :update, :destroy]
  before_action only: [:edit, :update, :destroy] do
    verify_owner @question
  end

  def show
    if current_user
      @answer = @question.answers.build
    end
  end

  def new
    if signed_out?
      redirect_to sign_in_path
    else
      @question = Question.new
    end
  end

  def create
    @question = current_user.questions.new(question_params)
    @question.user = current_user
    if @question.save
      flash[:success] = 'Question created successfully.'
      redirect_to question_path(@question)
    else
      flash.now[:danger] = 'Something went wrong.'
      render 'new'
    end
  end

  def edit
  end

  def update
    if @question.update(question_params)
      flash[:success] = "Question updated successfully."
      redirect_to question_path(@question)
    else
      flash[:danger] = "Something went wrong."
      render :edit
    end
  end

  def destroy
    @question.destroy
    flash[:success] = "Your question has been deleted."
    redirect_to root_path
  end

  private

  def question_params
    params.require(:question).permit(:body, :title, :image)
  end

  def set_question
    @question = Question.find_by(id: params[:id]) or not_found
  end

  def verify_owner(obj)
    if obj.user_id != current_user.id
      redirect_to question_path(obj)
    end
  end
end

app/views/questions/_form.html.erb
<% content_for :errors do %>
  <%= render partial: 'layouts/error', locals: { model: @question } %>
<% end %>

<%= form_for @question do |f| %>
  Title: <%= f.text_field :title, placeholder: "ask a question", required: true %>
  Question: <%= f.text_area :body, placeholder: "some details, please" %>
  Attachments: <%= f.file_field :image %><br>
  <%= f.submit "Ask a Question", class: "btn btn-primary" %>
<% end %><br>

app/views/questions/_question.html.erb
  <div>
    <h1><%= link_to question.title, question_path(question) %></h1>
    <p>
    <%= question.body %><br>
    <% if question.image.attached? %>
      <p><%= image_tag question.image.variant(resize_to_limit: [100,100]) %></p>
    <% end %>
    </p>
    <em>asked
    <%= link_to question do %> 
      <%= time_ago_in_words(question.created_at) %> ago
    <% end %> by
    <% if owner?(question) %> you </em><br>
      <%= link_to '[Edit]', edit_question_path(question) %> 
      <%= link_to '[Delete]', question_path(question), method: :delete, data: { confirm: 'Are you sure?' } %>
    <% else %>
      <%= link_to question.username, question.user %></em>
    <% end %>
    <br>
  </div>

app/views/questions/edit.html.erb
<h1>Edit a Question</h1>
<%= render partial: '/questions/form' %>

app/views/questions/new.html.erb
<h1>Ask a Question</h1>
<%= render partial: '/questions/form' %>

app/views/questions/show.html.erb
<%= render partial: 'question', locals: { question: @question } %>
<hr>
<h3><strong><center>ANSWERS</center></strong></h3><br>
<% if @question.answers.count > 0 %>
  <% @question.answers.each do |answer| %>
    <% if answer.user != nil %>
      <%= render partial: 'answers/answer', locals: { answer: answer } %><br>
    <% end %>
  <% end %>
<% else %>
  <p><em>Looks like no one has answered this question yet! Be the first.</em></p>
<% end %>

<h3><strong><center>ADD AN ANSWER</center></strong></h3><br>
<%= form_for [@question, @answer] do |f| %>
  <%= f.label :content, "Reply:" %><br>
  <%= f.text_area :content %>
  <%= f.submit "Submit answer", class: "btn btn-primary" %>
<% end %>