config/routes.rb
Rails.application.routes.draw do
  constraints Clearance::Constraints::SignedIn.new do
    root to: "dashboards#show", as: :signed_in_root
  end

  constraints Clearance::Constraints::SignedOut.new do
    root to: "homes#show"
  end
  
  resources :questions, except: [:index] do
    resources :answers, except: [:index]
  end

  resources :answers do
    member do
      post "upvote" => "upvotes#create", as: :upvote
      delete "unvote" => "upvotes#destroy", as: :unvote
    end
  end

  resources :passwords, controller: "clearance/passwords", only: [:create, :new]
  resource :session, only: [:create]

  resources :users, only: [:create, :show, :edit, :update] do
    resource :password,
      controller: "clearance/passwords",
      only: [:create, :edit, :update]
  end

  get "/sign_in" => "sessions#new", as: "sign_in"
  delete "/sign_out" => "sessions#destroy", as: "sign_out"
  get "/sign_up" => "users#new", as: "sign_up"
  get "/auth/:provider/callback" => "sessions#create_from_omniauth"
  get "/unanswered" => "dashboards#unanswered", as: "unanswered"
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :user
  belongs_to :question
  has_one_attached :image

  validates :content, presence: true
  validates :user, presence: true

  default_scope { order(created_at: :desc) }
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  before_action :set_answer, only: [:edit, :update, :destroy]
  before_action only: [:edit, :update, :destroy] do
    verify_owner @answer
  end

  def show
  end

  def new
    if signed_out?
      redirect_to sign_in_path
    else
      @answer = Answer.new
      @question = Question.find_by(id: params[:question_id])
    end
  end

  def create
    @answer = current_user.answers.build(answer_params)
    @answer.question_id = params[:question_id]
    if @answer.save
      flash[:success] = 'Answer created successfully!'
      redirect_to @answer.question
    else
      flash[:danger] = 'Something went wrong.'
      redirect_to @answer.question
    end
  end

  def edit
    @answer = Answer.find_by(id: params[:id])
    @question = Question.find_by(id: params[:question_id])
  end

  def update
    if @answer.update(answer_params)
      flash[:success] = "Answer updated successfully."
      redirect_to @answer.question
    else
      flash[:danger] = "Something went wrong."
      render @answer.question
    end
  end

  def destroy
    @answer.destroy
    flash[:success] = "Your answer has been deleted."
    redirect_to @answer.question
  end

  private

  def answer_params
    params.require(:answer).permit(:content, :image, :question_id, :user_id)
  end

  def set_answer
    @answer = Answer.find_by(id: params[:id]) or not_found
  end

  def verify_owner(obj)
    if obj.user_id != current_user.id
      redirect_to obj.question
    end
  end
end

app/helpers/answer_helper.rb
module AnswerHelper
  def vote_button(answer)
    if current_user.upvoted?(answer)
      link_to "Unvote", unvote_answer_path(answer.id), method: :delete
    else
      link_to "Upvote", upvote_answer_path(answer.id), method: :post
    end
  end
end

app/views/answers/_answer.html.erb
<div>
  <%= link_to answer.user.username, user_path(answer.user.username) %> wrote:
  <p><%= answer.content %></p>
  <em>answered <%= link_to question_path(answer.question_id) do %>
    <%= time_ago_in_words(answer.created_at) %> ago
  <% end %></em><br>
  <%= vote_button(answer) %> 
  <% if owner?(answer) %> || 
    <%= link_to '[Edit]', edit_question_answer_path(answer.question, answer) %>
    <%= link_to '[Delete]', answer_path(answer), method: :delete, data: { confirm: 'Are you sure?' } %>
  <% end %>
  <hr>
</div>

app/views/answers/_form.html.erb
<% content_for :errors do %>
  <%= render partial: 'layouts/error', locals: { model: @answer } %>
<% end %>

<div>
  <%= form_for(answer) do |f| %>
    Reply: 
    <%= f.text_field :content, placeholder: "answer here", required: true %>
    <%= f.submit "Submit answer", class: "btn btn-primary" %>
  <% end %>
</div>

app/views/answers/edit.html.erb
<%= render partial: 'questions/question', locals: { question: @question } %>
<hr>
<h3><strong><center>ANSWERS</center></strong></h3><br>
<% if @question.answers.count > 0 %>
  <% @question.answers.each do |answer| %>
    <% if answer.user != nil %>
      <%= render partial: 'answers/answer', locals: { answer: answer } %><br>
    <% end %>
  <% end %>
<% else %>
  <p><em>Looks like no one has answered this question yet! Be the first.</em></p>
<% end %>

<h3><strong><center>ADD AN ANSWER</center></strong></h3><br>
<%= form_for [@question, @answer] do |f| %>
  <%= f.label :content, "Reply:" %><br>
  <%= f.text_area :content %>
  <%= f.submit "Submit answer", class: "btn btn-primary" %>
<% end %>

app/views/answers/new.html.erb
<%= render partial: 'questions/question', locals: { question: @question } %>
<hr>
<h3><strong><center>ANSWERS</center></strong></h3><br>
<% if @question.answers.count > 0 %>
  <% @question.answers.each do |answer| %>
    <% if answer.user != nil %>
      <%= render partial: 'answers/answer', locals: { answer: answer } %><br>
    <% end %>
  <% end %>
<% else %>
  <p><em>Looks like no one has answered this question yet! Be the first.</em></p>
<% end %>

<h3><strong><center>ADD AN ANSWER</center></strong></h3><br>
<%= form_for [@question, @answer] do |f| %>
  <%= f.label :content, "Reply:" %><br>
  <%= f.text_area :content %>
  <%= f.submit "Submit answer", class: "btn btn-primary" %>
<% end %>