config/routes.rb
Rails.application.routes.draw do
  constraints Clearance::Constraints::SignedIn.new do
    root to: "dashboards#show", as: :signed_in_root
  end

  constraints Clearance::Constraints::SignedOut.new do
    root to: "homes#show"
  end
  
  resources :questions, except: [:index] do
    resources :answers, except: [:index]
  end

  resources :answers do
    member do
      post "upvote" => "upvotes#create", as: :upvote
      delete "unvote" => "upvotes#destroy", as: :unvote
    end
  end

  resources :passwords, controller: "clearance/passwords", only: [:create, :new]
  resource :session, only: [:create]

  resources :users, only: [:create, :show, :edit, :update] do
    resource :password,
      controller: "clearance/passwords",
      only: [:create, :edit, :update]
  end

  get "/sign_in" => "sessions#new", as: "sign_in"
  delete "/sign_out" => "sessions#destroy", as: "sign_out"
  get "/sign_up" => "users#new", as: "sign_up"
  get "/auth/:provider/callback" => "sessions#create_from_omniauth"
  get "/unanswered" => "dashboards#unanswered", as: "unanswered"
end

app/views/layouts/_error.html.erb
<% if model.errors.any? %>
  <div id="error_explanation"> 
    <div class="alert alert-danger">
      Oops! You made <%= pluralize(model.errors.count, "error") %>.
    </div>
    <ul>
      <% model.errors.full_messages.each do |m| %>
        <li><%= m %></li>
        <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    Made with love for the Flatiron School.
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",   '#' %></li>
      <li><%= link_to "Contact", '#' %></li>
      <li><a href="http://github.com/twwright/dashdashhelp">GitHub</a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
   <header class="navbar navbar-fixed-top navbar-inverse">
      <div class="container">
        <%= link_to "dashdashhelp", root_path, id: "logo" %>
        <nav>
          <ul class="nav navbar-nav navbar-right">
            <li><%= link_to "Home",   root_path %></li>
            <% if signed_in? %><li><%= link_to "Ask a Question", new_question_path %></li><% end %>
            <li><%= link_to "Answer a Question", unanswered_path %>
            <% if signed_in? %>
              <li><%= link_to current_user.username, user_path(current_user) %></li>
              <li><%= link_to 'Sign Out', sign_out_path, method: :delete %></li>
            <% else %>
              <li><%= link_to 'Sign up', sign_up_path %></li>
              <li><%= link_to 'Sign in', sign_in_path %></li>
              <li><%= link_to 'Sign in with Github', '/auth/github' %></li>
            <% end %>
          </ul>
        </nav>
      </div>
    </header>

app/views/layouts/_rails_head.html.erb
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

  <head>
    <title>Dashdashhelp</title>
    <%= render 'layouts/rails_head' %>
  </head>

  <body>
  <%= render 'layouts/header' %>
  
  <div class="container">
      <% flash.each do |type, msg| %>
        <%= content_tag :div, msg, class: "alert alert-#{type}" %>
      <% end %>
      <%= yield :errors %>

      <div class="row">
        <div class="col-md-6 col-md-offset-3">
        <%= yield %>
        </div>
      </div>
   </div>

  <%= render 'layouts/footer' %>
  <%# debug(params) if Rails.env.development? %>
  </body>
</html>